# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
from scipy import stats
import numpy as np

In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [3]:
GPU1mean = np.mean(GPU1)
GPUstd = np.std(GPU1, ddof=1)
t_statistic, p_value = stats.ttest_1samp(GPU1,0)
print("GPU1 Mean =" , GPU1mean)
print("GPU1 Std =" , GPUstd)
print("t_statistic =" , t_statistic)
print("p_value =" , p_value)

GPU1 Mean = 10.333333333333334
GPU1 Std = 1.1751393027860062
t_statistic = 34.056241516158195
p_value = 7.228892044970457e-15


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [4]:
tstat,pvalue = stats.ttest_ind(GPU1, GPU2, equal_var=False)
print(pvalue)
print(tstat)
print('Pvalue is < 0.05 i,e 1.3%')
if pvalue<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

0.013794876635369257
-2.627629513471839
Pvalue is < 0.05 i,e 1.3%
reject null hypothesis


## Question 3

He is trying a third GPU - GPU3.

In [5]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [6]:
t_statistic, p_value = stats.ttest_ind(GPU1, GPU3, equal_var=False)
print(t_statistic)
print(p_value)
if p_value<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

-1.4988943759093303
0.1456833060579751
accept null hypothesis


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [7]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [8]:
data_levene = stats.levene(e1,e2,e3)
print(data_levene)

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [9]:
stats.f_oneway(e1, e2, e3)

F_onewayResult(statistic=2.51357622845924, pvalue=0.13574644501798466)

## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

Type I error: 
When we reject the null hypothesis, although that hypothesis was true. Type I error is denoted by alpha. In hypothesis testing, the normal curve that shows the critical region is called the alpha region

Type II errors: 
When we accept the null hypothesis but it is false. Type II errors are denoted by beta. In Hypothesis testing, the normal curve that shows the acceptance region is called the beta region.

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


H0: Wait time to place order has changed(less or more) in past 1 month from 4.5 minutes

HA: Wait time to place order has not changed in past 1 month, still @4.5 minutes

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [10]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [11]:
chi_square_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(dice)
print(chi_square_Stat)
print(p_value)
print(deg_freedom)
print(exp_freq)

23.315671914716496
0.07766367301496693
15
[[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [12]:
mean_value = dice.mean()
print('Mean of Dice Array: %1.6f' %(mean_value))
stats.zscore(dice)

Mean of Dice Array: 6.458333


array([[-0.46291005, -0.18884739, -1.83711731,  1.44115338],
       [ 1.38873015, -0.64208114,  1.22474487,  0.        ],
       [ 0.9258201 ,  0.7176201 ,  0.61237244, -1.44115338],
       [-0.9258201 ,  1.62408759,  0.61237244, -0.96076892],
       [-1.38873015,  0.03776948,  0.        ,  0.        ],
       [ 0.46291005, -1.54854863, -0.61237244,  0.96076892]])

In [13]:
Z_score=stats.zscore(dice, axis=None, ddof=1)
p_values=stats.norm.sf(abs(Z_score),loc=0,scale=1)*2
print('Z_score :\n',Z_score)
print("Mean of Z_score = ",np.mean(Z_score))
print('p_values :\n',p_values)
print('Mean of array of p_values is %5.4f'%np.mean(p_values))

Z_score :
 [[-0.45530567  0.48132314 -1.07972488  0.48132314]
 [ 0.79353274 -0.14309607  0.48132314 -0.45530567]
 [ 0.48132314  1.73016155  0.16911354 -1.39193448]
 [-0.76751528  2.97899997  0.16911354 -1.07972488]
 [-1.07972488  0.79353274 -0.14309607 -0.45530567]
 [ 0.16911354 -1.39193448 -0.45530567  0.16911354]]
Mean of Z_score =  8.326672684688674e-17
p_values :
 [[0.64888935 0.63028685 0.28026471 0.63028685]
 [0.4274675  0.88621431 0.63028685 0.64888935]
 [0.63028685 0.08360142 0.86570734 0.16394224]
 [0.44277521 0.00289191 0.86570734 0.28026471]
 [0.28026471 0.4274675  0.88621431 0.64888935]
 [0.86570734 0.16394224 0.64888935 0.86570734]]
Mean of array of p_values is 0.5377


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [14]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [16]:
t_statistic, p_value  =  stats.ttest_rel(after, before )
print('P Value=', p_value)

P Value= 0.001471849691648716
